version: '3.11'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${PG_PASSWORD}
      PGUSER: ${PG_USER}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    networks:
      - mynetwork

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    networks:
      - mynetwork

networks:
      mynetwork:

volumes:
  db_data:
  pgadmin-data:
